name: Greetings

on:
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for opening your first issue in this project! If you haven't already, you can [join our slack](https://docs.google.com/forms/d/e/1FAIpQLSczZbZB9ql_Xl-1uBtmvYmA0fwfm1UX92SyWAdkuMEDfxac5w/viewform) and join the #mobility-database channel to meet our awesome community. Come say hi :wave:!<br><br> Welcome to the community and thank you for contributing! :tada:<br><br> ![](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)"
        pr-message: "Thanks for opening this pull request! You're awesome.<br>We use [semantic commit messages](https://github.com/electron/electron/blob/main/docs/development/pull-requests.md#commit-message-guidelines) to streamline the release process. Before your pull request can be merged, you should **update your pull request title** to start with a semantic prefix.<br>Examples of titles with semantic prefixes:<br>- `fix: Fix wrong countries for some sources`<br>- `feat: Add Features and Status to MDB Schema [SOURCES]`<br>- `docs: Improvements to README.md and CONTRIBUTING.md`<br><br>If your pull request includes adding or updating a source, make sure to **end your pull request title with \"[SOURCES]\"** so the GitHub workflow runs."
